
const eras = [
  {
    attachments: '',
    center: '',
    dates: [1502, 1808],
    description: '',
    increment: 1,
    name: 'Colonial Rule',
    notes: '',
    zoom: '',
  },
  {
    attachments: '',
    center: '',
    dates: [1808, 1821],
    description: '',
    increment: 1,
    name: 'Royal Rule',
    notes: '',
    zoom: '',
  },
  {
    attachments: '',
    center: '',
    dates: [1822, 1831],
    description: '',
    increment: 1,
    name: 'Imperial Rule I',
    notes: '',
    zoom: '',
  },
  {
    attachments: '',
    center: '',
    dates: [1831, 1839],
    description: '',
    increment: 1,
    name: 'Regency',
    notes: '',
    zoom: '',
  },
  {
    attachments: '',
    center: '',
    dates: [1840, 1889],
    description: '',
    increment: 1,
    name: 'Imperial Rule II',
    notes: '',
    zoom: '',
  },
  {
    attachments: '',
    center: '',
    dates: [1889, 1930],
    description: '',
    increment: 1,
    name: 'First Republic',
    notes: '',
    zoom: '',
  },
  {
    attachments: '',
    center: '',
    dates: [1930, 1945],
    description: '',
    increment: 1,
    name: 'Vargas Era',
    notes: '',
    zoom: '',
  },
  {
    attachments: '',
    center: '',
    dates: [1946, 1964],
    description: '',
    increment: 1,
    name: 'Democratic Interlude',
    notes: '',
    zoom: '',
  },
  {
    attachments: '',
    center: '',
    dates: [1964, 1985],
    description: '',
    increment: 1,
    name: 'Military Dictatorship',
    notes: '',
    zoom: '',
  },
  {
    attachments: '',
    center: '',
    dates: [1985, new Date().getFullYear()],
    description: '',
    increment: 1,
    name: 'New Republic',
    notes: '',
    zoom: '',
  },
];

// _.reduce(eras, (m, e) => m + Math.round((e.dates[1] - e.dates[0]) / e.increment), 0);

export default eras;
